name: 🐛 Bug Report
description: Report a bug in Kitt-Cues
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - sanchousmutant

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🎱
        
        Please provide as much detail as possible to help us fix the issue.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Kitt-Cues are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop (Windows)
        - Desktop (Mac)
        - Desktop (Linux)
        - Mobile (iOS)
        - Mobile (Android)
        - Tablet (iOS)
        - Tablet (Android)
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Safari Mobile
        - Chrome Mobile
        - Samsung Internet
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The game crashes when..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to the game
        2. Click on...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "The ball should..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Drag and drop images here or paste links"

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any error messages from browser console (F12)
      placeholder: "Paste any console errors here"

  - type: checkboxes
    id: game-features
    attributes:
      label: Affected Features
      description: Which game features are affected?
      options:
        - label: Ball physics
        - label: Cat interactions
        - label: Sound effects
        - label: UI controls
        - label: Mobile controls
        - label: Scoring system
        - label: PWA features

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here