name: ✨ Feature Request
description: Suggest a new feature for Kitt-Cues
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
assignees:
  - sanchousmutant

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        
        We'd love to hear your ideas to make Kitt-Cues even better.

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Game Mechanics
        - Cat Behaviors
        - Audio/Sound
        - User Interface
        - Mobile Experience
        - Accessibility
        - Performance
        - PWA Features
        - Other
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: problem-solving
    attributes:
      label: Problem This Solves
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "The feature could work by..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions or features you've considered?
      placeholder: "Alternatively, we could..."

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: checkboxes
    id: implementation-areas
    attributes:
      label: Implementation Areas
      description: Which parts of the game would this affect?
      options:
        - label: TypeScript modules
        - label: Physics engine
        - label: Sound system
        - label: UI components
        - label: Mobile optimization
        - label: Build process
        - label: Testing

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Any mockups, sketches, or examples of similar features?
      placeholder: "Links to examples or drag and drop images here"

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: Yes, I can help with the implementation
        - label: Yes, I can help with testing
        - label: Yes, I can help with documentation
        - label: I can provide feedback during development

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here